[build]
publish = "Task2"


[[redirects]]
from = "/task2"
to = "/task2.html"
status = 200
[[redirects]]
from = "/slider"
to = "/Slider.html"
status = 200
[[redirects]]
from = "/*"
to = "/task2.html"
status = 200
